backend:
    name: git-gateway
    branch: master
    repo: Brightside-Technologies/iq
accepted_roles:
    - Administrator
    - Editor
display_url: https://iq.netlify.com/
# logo_url: https://bgcofcv.netlify.com/assets/images/hero-logo.png
media_folder: static/uploads
public_folder: static/uploads
collections:
    - name: global
      label: Site Settings
      delete: false
      description: Settings that are used throughout the entire site
      extension: json
      files:
          - file: _data/_metadata.json
            label: Metadata
            name: site
            editor:
                preview: false
            fields:
                - label: Site Title
                  name: site_title
                  widget: string
                  hint: Used for SEO
                - label: Default Site Description
                  name: default_site_description
                  widget: text
                  hint: Used for SEO
                - label: Email
                  name: email
                  widget: string
                - label: Twitter Url
                  name: twitter_url
                  widget: string
                - label: Twitter Username
                  name: twitter_username
                  widget: string
                - label: Facebook Url
                  name: facebook_url
                  widget: string
                - label: Instagram Url
                  name: instagram_url
                  widget: string
                - label: Open Graph Image
                  name: open_graph_image
                  widget: image
                  default: static/uploads/preview.jpg
                  hint: This is the thumbnail that shows up when you share your site on Facebook or via an iMessage

    - name: pages
      label: Pages
      delete: false
      create: false
      description: Manage site's page content
      extension: json
      files:
          - file: _data/_pages/_home.json
            label: Home
            name: home
            editor:
                preview: false
            fields:
                - label: Page Title
                  name: title
                  widget: string
                - label: Page Description
                  name: description
                  widget: text
                  hint: Used for SEO
                - label: Greeting
                  name: greeting
                  widget: markdown
                - label: Tagline
                  name: tagline
                  widget: markdown
                - label: Picture
                  name: profile_image
                  widget: image

          - file: _data/_pages/_bio.json
            label: Bio
            name: bio
            editor:
                preview: false
            fields:
                - label: Page Title
                  name: title
                  widget: string
                - label: Page Description
                  name: description
                  widget: text
                  hint: Used for SEO
                - label: About Me
                  name: about_me
                  widget: markdown
                - label: Quote
                  name: blockquote
                  widget: object
                  hint: Important quote to display on Home page header
                  fields:
                      - label: Quote
                        name: content
                        widget: markdown
                      - label: Source
                        name: source
                        widget: object
                        fields:
                            - label: Person
                              name: person
                              widget: string
                              required: false
                              hint: Name of the person who gave the quote
                            - label: Picture
                              name: image
                              widget: image
                              required: false
                              hint: Optional - Could be the picture of the person or the company's logo. Here, you are actually uploading the picture.
                            - label: Picture Link
                              name: image
                              widget: string
                              required: false
                              hint: Optional - Could be the picture of the person or the company's logo. This is just the link to an image you might find online.
                            - label: Company
                              name: company
                              widget: string
                              required: false
                              hint: Optionally, you can name a company in addition to/instead of a person
                - label: Awards
                  name: awards
                  widget: list
                  fields:
                      - label: Award Name
                        name: name
                        widget: string
                      - label: Link
                        name: link
                        widget: string
                        required: false
                        hint: Optional - you can provide a url for more information about the award
                      - label: Description
                        name: description
                        widget: markdown
                        required: false
                        hint: Optional
                      - label: Date
                        name: date
                        widget: string
                        hint: Year award was received

          - file: _data/_pages/_work.json
            label: My Work
            name: work
            editor:
                preview: false
            fields:
                - label: Page Title
                  name: title
                  widget: string
                - label: Page Description
                  name: description
                  widget: text
                  hint: Used for SEO
                - label: Content
                  name: content
                  widget: markdown
                - label: List of Work
                  name: works
                  widget: list
                  fields:
                      - label: Title
                        name: title
                        widget: string
                      - label: Description
                        name: description
                        widget: markdown
                      - label: Picture
                        name: image
                        widget: image
                      - label: Link
                        name: link
                        widget: string
                        hint: Link to more information about your work, where to buy, etc.
                      - label: Publish Date
                        name: publish_date
                        widget: date
                        default: ""
                        format: "YYYY"
                      - label: Blurb
                        name: blurb
                        widget: object
                        hint: Blurb about your work
                        required: false
                        fields:
                            - label: Quote
                              name: content
                              widget: markdown
                            - label: Source
                              name: source
                              widget: object
                              fields:
                                  - label: Person
                                    name: person
                                    widget: string
                                    required: false
                                    hint: Name of the person who gave the quote
                                  - label: Picture
                                    name: image
                                    widget: image
                                    required: false
                                    hint: Optional - Could be the picture of the person or the company's logo. Here, you are actually uploading the picture.
                                  - label: Picture Link
                                    name: image
                                    widget: string
                                    required: false
                                    hint: Optional - Could be the picture of the person or the company's logo. This is just the link to an image you might find online.
                                  - label: Company
                                    name: company
                                    widget: string
                                    required: false
                                    hint: Optionally, you can name a company in addition to/instead of a person
                      - label: Publisher
                        name: publisher
                        hint: Publisher information
                        widget: object
                        fields:
                            - label: Name
                              name: name
                              widget: string
                            - label: Url
                              name: url
                              widget: string
                            - label: Logo
                              name: logo
                              widget: string
                              hint: Url of publisher's image

          - file: _data/_pages/_events.json
            label: Events
            name: events
            editor:
                preview: false
            fields:
                - label: Page Title
                  name: title
                  widget: string
                - label: Page Description
                  name: description
                  widget: text
                  hint: Used for SEO
                - label: Content
                  name: content
                  widget: markdown
                - label: Events
                  name: events
                  widget: list
                  fields:
                      - label: Title
                        name: title
                        widget: string
                      - label: Description
                        name: description
                        widget: markdown
                      - label: Link
                        name: url
                        widget: string
                        hint: Link to more information about event.
                      - label: Start
                        name: start
                        widget: datetime
                        default: ""
                        format: ""
                      - label: End
                        name: end
                        widget: datetime
                        default: ""
                        format: ""
                      - label: Location
                        name: location
                        widget: string
                      - label: Address
                        name: address
                        widget: string
                      - label: Event Picture
                        name: photo_url
                        widget: string
                        hint: Url to image of event promotion or flyer
                      - label: Event Picture
                        name: photo_url
                        widget: image
                        hint: Uploaded image
