backend:
    name: git-gateway
    branch: master
    repo: Brightside-Technologies/iq
accepted_roles:
    - Administrator
    - Editor
display_url: https://iq.netlify.com/
# logo_url: https://bgcofcv.netlify.com/assets/images/hero-logo.png
media_folder: static/uploads
public_folder: static/uploads
collections:
    - name: global
      label: Site Settings
      delete: false
      description: Settings that are used throughout the entire site
      extension: json
      files:
          - file: _data/_metadata.json
            label: Metadata
            name: site
            editor:
                preview: false
            fields:
                - label: Site Title
                  name: site_title
                  widget: string
                  hint: Used for SEO
                - label: Default Site Description
                  name: default_site_description
                  widget: text
                  hint: Used for SEO
                - label: Email
                  name: email
                  widget: string
                - label: Twitter Url
                  name: twitter_url
                  widget: string
                - label: Twitter Username
                  name: twitter_username
                  widget: string
                - label: Facebook Url
                  name: facebook_url
                  widget: string
                - label: Instagram Url
                  name: instagram_url
                  widget: string
                - label: Open Graph Image
                  name: open_graph_image
                  widget: image
                  default: static/uploads/preview.jpg
                  hint: This is the thumbnail that shows up when you share your site on Facebook or via an iMessage

    - name: pages
      label: Pages
      delete: false
      create: false
      description: Manage site's page content
      extension: json
      files:
          - file: _data/_pages/_bio.json
            label: Bio
            name: bio
            fields:
                - label: Page Title
                  name: title
                  widget: string
                - label: Page Description
                  name: description
                  widget: text
                  hint: Used for SEO
                - label: About Me
                  name: about_me
                  widget: markdown
                - label: Quote
                  name: blockquote
                  widget: object
                  hint: Important quote to display on Home page header
                  fields:
                      - label: Quote
                        name: content
                        widget: markdown
                      - label: Source
                        name: source
                        widget: object
                        fields:
                            - label: Person
                              name: person
                              widget: string
                              required: false
                              hint: Name of the person who gave the quote
                            - label: Picture
                              name: image
                              widget: image
                              required: false
                              hint: Optional - Could be the picture of the person or the company's logo. Here, you are actually uploading the picture.
                            - label: Picture Link
                              name: image
                              widget: string
                              required: false
                              hint: Optional - Could be the picture of the person or the company's logo. This is just the link to an image you might find online.
                            - label: Company
                              name: company
                              widget: string
                              required: false
                              hint: Optionally, you can name a company in addition to/instead of a person
                - label: Awards
                  name: awards
                  widget: list
                  fields:
                      - label: Award Name
                        name: name
                        widget: string
                      - label: Link
                        name: link
                        widget: string
                        required: false
                        hint: Optional - you can provide a url for more information about the award
                      - label: Description
                        name: description
                        widget: markdown
                        required: false
                        hint: Optional
                      - label: Date
                        name: name
                        widget: string
                        hint: Year award was received
